### ISSUE TITLE
Не работает requirements.txt на Windows

### ISSUE THREAD

**Issue by ArtiomNosov** [IT-Continue/simple-password-cli#13]
Устройство

> Процессор	Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz   1.99 GHz
> Оперативная память	16,0 ГБ (доступно: 15,8 ГБ)
> Код устройства	8C6A7FCB-D0A5-463D-ACD2-9775C3535B33
> Код продукта	00330-52678-21927-AAOEM
> Тип системы	64-разрядная операционная система, процессор x64

OS

> Выпуск	Windows 10 Pro
> Версия	22H2
> Дата установки	‎20.‎03.‎2024
> Сборка ОС	19045.4412
> Взаимодействие	Windows Feature Experience Pack 1000.19056.1000.0

Python

> Python 3.12.2

Воспроизведение ошибки
```
Microsoft Windows [Version 10.0.19045.4412]
(c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

C:\Users\nosov_ar>call "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Scripts\activate.bat" ""
Системе не удается найти указанный путь.

C:\Users\nosov_ar>cd "call "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Scripts\activate.bat" """
Синтаксическая ошибка в имени файла, имени папки или метке тома.

C:\Users\nosov_ar>cd "C:\Program Files (x86)\Simple-Password-Gen-main"

C:\Program Files (x86)\Simple-Password-Gen-main>python3 -m venv venv

C:\Program Files (x86)\Simple-Password-Gen-main>.\venv\Scripts\activate.bat

(venv) C:\Program Files (x86)\Simple-Password-Gen-main>pip3 install -r requirements.txt
```
Ошибка

```
Collecting argon2-cffi==21.3.0 (from -r requirements.txt (line 1))
  Downloading argon2_cffi-21.3.0-py3-none-any.whl.metadata (5.4 kB)
Collecting argon2-cffi-bindings==21.2.0 (from -r requirements.txt (line 2))
  Using cached argon2_cffi_bindings-21.2.0-cp36-abi3-win_amd64.whl.metadata (6.7 kB)
Collecting ascii-magic==1.6 (from -r requirements.txt (line 3))
  Downloading ascii_magic-1.6-py3-none-any.whl.metadata (9.3 kB)
Collecting cffi==1.15.1 (from -r requirements.txt (line 4))
  Downloading cffi-1.15.1.tar.gz (508 kB)
     ---------------------------------------- 508.5/508.5 kB 741.5 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting colorama==0.4.6 (from -r requirements.txt (line 5))
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting contourpy==1.0.7 (from -r requirements.txt (line 6))
  Downloading contourpy-1.0.7.tar.gz (13.4 MB)
     ---------------------------------------- 13.4/13.4 MB 691.2 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cycler==0.11.0 (from -r requirements.txt (line 7))
  Downloading cycler-0.11.0-py3-none-any.whl.metadata (785 bytes)
Collecting fonttools==4.43.0 (from -r requirements.txt (line 8))
  Downloading fonttools-4.43.0-cp312-cp312-win_amd64.whl.metadata (154 kB)
     ---------------------------------------- 155.0/155.0 kB 841.4 kB/s eta 0:00:00
Collecting kiwisolver==1.4.4 (from -r requirements.txt (line 9))
  Downloading kiwisolver-1.4.4.tar.gz (97 kB)
     ---------------------------------------- 97.1/97.1 kB 347.4 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting matplotlib==3.7.0 (from -r requirements.txt (line 10))
  Downloading matplotlib-3.7.0.tar.gz (36.3 MB)
     ---------------------------------------- 36.3/36.3 MB 962.2 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy==1.24.2 (from -r requirements.txt (line 11))
  Downloading numpy-1.24.2.tar.gz (10.9 MB)
     ---------------------------------------- 10.9/10.9 MB 204.4 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\cli\req_command.py", line 245, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
           ^^^^^^^^^
  File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
                ^^^^^^
  File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 182, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 228, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 290, in __init__
    super().__init__(
  File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 222, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 301, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\operations\prepare.py", line 525, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\operations\prepare.py", line 640, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\operations\prepare.py", line 71, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\distributions\sdist.py", line 54, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\distributions\sdist.py", line 124, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\distributions\sdist.py", line 101, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\utils\misc.py", line 745, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\nosov_ar\AppData\Local\Temp\pip-build-env-hehdcrpm\overlay\Lib\site-packages\setuptools\__init__.py", line 10, in <module>
    import distutils.core
ModuleNotFoundError: No module named 'distutils'
```

**Comment by GregoryKogan** [comment]
`distutils` package is removed in `python version 3.12`

Try running `pip3 install setuptools` before `pip3 install -r requirements.txt`.
Does it help?

**Comment by ArtiomNosov** [comment]
Я вручную ставил каждую зависимость из requirements.txt

> argon2-cffi==21.3.0
> argon2-cffi-bindings==21.2.0
> ascii-magic==1.6
> cffi==1.15.1
> colorama==0.4.6
> contourpy==1.0.7
> cycler==0.11.0
> fonttools==4.43.0
> kiwisolver==1.4.4
> matplotlib==3.7.0
> numpy==1.24.2
> packaging==23.0
> perlin-noise==1.12
> Pillow==10.3.0
> prompt-toolkit==3.0.36
> pycparser==2.21
> pycryptodome==3.19.1
> pyparsing==3.0.9
> python-dateutil==2.8.2
> questionary==1.10.0
> six==1.16.0
> termcolor==2.2.0
> wcwidth==0.2.6

Не получилось поставить `numpy==1.24.2`, но и без него приложение заработало и выдало мне пароль
Ошибка установки `numpy==1.24.2`

> (venv) C:\Program Files (x86)\Simple-Password-Gen-main>pip install numpy==1.24.2
> Collecting numpy==1.24.2
>   Using cached numpy-1.24.2.tar.gz (10.9 MB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
> ERROR: Exception:
> Traceback (most recent call last):
>   File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
>     status = run_func(*args)
>              ^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\cli\req_command.py", line 245, in wrapper
>     return func(self, options, args)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\commands\install.py", line 377, in run
>     requirement_set = resolver.resolve(
>                       ^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
>     result = self._result = resolver.resolve(
>                             ^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
>     state = resolution.resolve(requirements, max_rounds=max_rounds)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
>     self._add_to_criteria(self.state.criteria, r, parent=None)
>   File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
>     if not criterion.candidates:
>            ^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
>     return bool(self._sequence)
>            ^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
>     return any(self)
>            ^^^^^^^^^
>   File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
>     return (c for c in iterator if id(c) not in self._incompatible_ids)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
>     candidate = func()
>                 ^^^^^^
>   File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 182, in _make_candidate_from_link
>     base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
>                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 228, in _make_base_candidate_from_link
>     self._link_candidate_cache[link] = LinkCandidate(
>                                        ^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 290, in __init__
>     super().__init__(
>   File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
>     self.dist = self._prepare()
>                 ^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 222, in _prepare
>     dist = self._prepare_distribution()
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 301, in _prepare_distribution
>     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\operations\prepare.py", line 525, in prepare_linked_requirement
>     return self._prepare_linked_requirement(req, parallel_builds)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\operations\prepare.py", line 640, in _prepare_linked_requirement
>     dist = _get_prepared_distribution(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\operations\prepare.py", line 71, in _get_prepared_distribution
>     abstract_dist.prepare_distribution_metadata(
>   File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\distributions\sdist.py", line 54, in prepare_distribution_metadata
>     self._install_build_reqs(finder)
>   File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\distributions\sdist.py", line 124, in _install_build_reqs
>     build_reqs = self._get_build_requires_wheel()
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\distributions\sdist.py", line 101, in _get_build_requires_wheel
>     return backend.get_requires_for_build_wheel()
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_internal\utils\misc.py", line 745, in get_requires_for_build_wheel
>     return super().get_requires_for_build_wheel(config_settings=cs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
>     return self._call_hook('get_requires_for_build_wheel', {
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
>     raise BackendUnavailable(data.get('traceback', ''))
> pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
>   File "C:\Program Files (x86)\Simple-Password-Gen-main\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
>     obj = import_module(mod_path)
>           ^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 90, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
>   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>   File "C:\Users\nosov_ar\AppData\Local\Temp\pip-build-env-mszlq0or\overlay\Lib\site-packages\setuptools\__init__.py", line 10, in <module>
>     import distutils.core
> ModuleNotFoundError: No module named 'distutils'

Хотел бы закрыть ишью, так как без этой библиотеки работает, но хочу увидеть одобрение @GregoryKogan , что можно из requirements.txt выпилить `numpy==1.24.2` без нарушения работы приложения

**Comment by GregoryKogan** [comment]
> можно из requirements.txt выпилить `numpy==1.24.2` без нарушения работы приложения

`numpy`dependency removed in [this commit](https://github.com/IT-Continue/simple-password-cli/commit/fa96c733601809afa9c78d33a8f40cdaf52ae914)
